// Generated by code_gen.py on 2026-02-26T21:59:58.680949
#ifndef PDR_GENERATED_H_
#define PDR_GENERATED_H_

#include <stdint.h>
#include <stddef.h>
#include "pldm_pdr_repo.h"

// --- Bound Macros ---
#define Tinhhayho 1
#define sensor 256
#define SENSOR_ENTITY_TYPE_NUMERIC0 42
#define STATE_SENSOR_STATE0_POSSIBLE 3
#define EFFECTER_ID_NUMERIC0 300
#define OEM_STATE_SET_ID 32968
#define SENSOR_INIT_SENSOR_ID 257
#define SENSOR_INIT_TERMINUS_HANDLE 256
#define SENSOR_INIT_UPPER_WARN 100
#define SENSOR_INIT_UPPER_CRIT 120
#define SENSOR_INIT_UPPER_FATAL 150
#define SENSOR_INIT_LOWER_WARN 50
#define SENSOR_INIT_LOWER_CRIT 30
#define SENSOR_INIT_LOWER_FATAL 10

#define PDR_BLOB_CAPACITY      1480
#define PDR_BLOB_DATA_SIZE     1184
#define PDR_HEADER_SIZE        10  // common PDR header: 4+1+1+2+2

// --- PDR Statistics ---
#define PDR_COUNT              30
#define PDR_TYPE_COUNT         28
#define PDR_MAX_RECORD_SIZE    90  // header + body
#define PDR_MIN_RECORD_SIZE    19
#define PDR_MAX_BODY_SIZE      80  // body only
#define PDR_MIN_BODY_SIZE      9
#define PDR_MAX_HANDLE         131
#define PDR_MIN_HANDLE         1

// --- Per-Type Record Counts ---
#define PDR_TYPE1_COUNT       2
#define PDR_TYPE2_COUNT       1
#define PDR_TYPE3_COUNT       1
#define PDR_TYPE4_COUNT       1
#define PDR_TYPE5_COUNT       1
#define PDR_TYPE6_COUNT       1
#define PDR_TYPE7_COUNT       1
#define PDR_TYPE8_COUNT       1
#define PDR_TYPE9_COUNT       1
#define PDR_TYPE10_COUNT       1
#define PDR_TYPE11_COUNT       1
#define PDR_TYPE12_COUNT       1
#define PDR_TYPE13_COUNT       1
#define PDR_TYPE14_COUNT       1
#define PDR_TYPE15_COUNT       2
#define PDR_TYPE16_COUNT       1
#define PDR_TYPE17_COUNT       1
#define PDR_TYPE18_COUNT       1
#define PDR_TYPE19_COUNT       1
#define PDR_TYPE20_COUNT       1
#define PDR_TYPE21_COUNT       1
#define PDR_TYPE22_COUNT       1
#define PDR_TYPE23_COUNT       1
#define PDR_TYPE24_COUNT       1
#define PDR_TYPE25_COUNT       1
#define PDR_TYPE30_COUNT       1
#define PDR_TYPE126_COUNT       1
#define PDR_TYPE127_COUNT       1

// --- Per-Record Handle / Offset / Size ---
#define PDR_HANDLE_TERMINUS    1
#define PDR_OFFSET_TERMINUS    0
#define PDR_SIZE_TERMINUS      35  // body=25
#define PDR_HANDLE_TYPE_1    1
#define PDR_OFFSET_TYPE_1    35
#define PDR_SIZE_TYPE_1      35  // body=25
#define PDR_HANDLE_TYPE_2    2
#define PDR_OFFSET_TYPE_2    70
#define PDR_SIZE_TYPE_2      69  // body=59
#define PDR_HANDLE_TYPE_3    3
#define PDR_OFFSET_TYPE_3    139
#define PDR_SIZE_TYPE_3      24  // body=14
#define PDR_HANDLE_TYPE_4    4
#define PDR_OFFSET_TYPE_4    163
#define PDR_SIZE_TYPE_4      31  // body=21
#define PDR_HANDLE_TYPE_5    5
#define PDR_OFFSET_TYPE_5    194
#define PDR_SIZE_TYPE_5      28  // body=18
#define PDR_HANDLE_TYPE_6    6
#define PDR_OFFSET_TYPE_6    222
#define PDR_SIZE_TYPE_6      43  // body=33
#define PDR_HANDLE_TYPE_7    7
#define PDR_OFFSET_TYPE_7    265
#define PDR_SIZE_TYPE_7      46  // body=36
#define PDR_HANDLE_TYPE_8    8
#define PDR_OFFSET_TYPE_8    311
#define PDR_SIZE_TYPE_8      58  // body=48
#define PDR_HANDLE_TYPE_9    9
#define PDR_OFFSET_TYPE_9    369
#define PDR_SIZE_TYPE_9      62  // body=52
#define PDR_HANDLE_TYPE_10    10
#define PDR_OFFSET_TYPE_10    431
#define PDR_SIZE_TYPE_10      19  // body=9
#define PDR_HANDLE_TYPE_11    11
#define PDR_OFFSET_TYPE_11    450
#define PDR_SIZE_TYPE_11      33  // body=23
#define PDR_HANDLE_TYPE_12    12
#define PDR_OFFSET_TYPE_12    483
#define PDR_SIZE_TYPE_12      32  // body=22
#define PDR_HANDLE_TYPE_13    13
#define PDR_OFFSET_TYPE_13    515
#define PDR_SIZE_TYPE_13      39  // body=29
#define PDR_HANDLE_TYPE_14    14
#define PDR_OFFSET_TYPE_14    554
#define PDR_SIZE_TYPE_14      19  // body=9
#define PDR_HANDLE_TYPE_15    15
#define PDR_OFFSET_TYPE_15    573
#define PDR_SIZE_TYPE_15      26  // body=16
#define PDR_HANDLE_TYPE_16    16
#define PDR_OFFSET_TYPE_16    599
#define PDR_SIZE_TYPE_16      46  // body=36
#define PDR_HANDLE_TYPE_17    17
#define PDR_OFFSET_TYPE_17    645
#define PDR_SIZE_TYPE_17      21  // body=11
#define PDR_HANDLE_TYPE_18    18
#define PDR_OFFSET_TYPE_18    666
#define PDR_SIZE_TYPE_18      46  // body=36
#define PDR_HANDLE_TYPE_19    19
#define PDR_OFFSET_TYPE_19    712
#define PDR_SIZE_TYPE_19      19  // body=9
#define PDR_HANDLE_TYPE_20    20
#define PDR_OFFSET_TYPE_20    731
#define PDR_SIZE_TYPE_20      20  // body=10
#define PDR_HANDLE_TYPE_21    21
#define PDR_OFFSET_TYPE_21    751
#define PDR_SIZE_TYPE_21      59  // body=49
#define PDR_HANDLE_TYPE_22    22
#define PDR_OFFSET_TYPE_22    810
#define PDR_SIZE_TYPE_22      90  // body=80
#define PDR_HANDLE_TYPE_23    23
#define PDR_OFFSET_TYPE_23    900
#define PDR_SIZE_TYPE_23      26  // body=16
#define PDR_HANDLE_TYPE_24    24
#define PDR_OFFSET_TYPE_24    926
#define PDR_SIZE_TYPE_24      62  // body=52
#define PDR_HANDLE_TYPE_25    25
#define PDR_OFFSET_TYPE_25    988
#define PDR_SIZE_TYPE_25      56  // body=46
#define PDR_HANDLE_TYPE_30    30
#define PDR_OFFSET_TYPE_30    1044
#define PDR_SIZE_TYPE_30      59  // body=49
#define PDR_HANDLE_TYPE_126    126
#define PDR_OFFSET_TYPE_126    1103
#define PDR_SIZE_TYPE_126      27  // body=17
#define PDR_HANDLE_TYPE_127    127
#define PDR_OFFSET_TYPE_127    1130
#define PDR_SIZE_TYPE_127      22  // body=12
#define PDR_HANDLE_TYPE_15_DOC_HIDDEN    131
#define PDR_OFFSET_TYPE_15_DOC_HIDDEN    1152
#define PDR_SIZE_TYPE_15_DOC_HIDDEN      32  // body=22

// --- X-Macro: list of all PDR types present ---
//
// PDR_TYPE_ENTRY(type, count)
//   type  - PDR type number (e.g., 1 = Terminus Locator, 2 = Numeric Sensor)
//   count - number of records of that type in this repository
//
// Example 1: Build a lookup table
//
//   static const struct { uint8_t type; uint8_t count; } pdr_types[] = {
//   #define PDR_TYPE_ENTRY(type, count) { type, count },
//       PDR_TYPE_LIST
//   #undef PDR_TYPE_ENTRY
//   };
//
// Example 2: Check if a PDR type exists
//
//   bool is_known_pdr_type(uint8_t t) {
//   #define PDR_TYPE_ENTRY(type, count) if (t == type) return true;
//       PDR_TYPE_LIST
//   #undef PDR_TYPE_ENTRY
//       return false;
//   }
//
// Example 3: Get record count for a type in a switch
//
//   uint8_t pdr_type_record_count(uint8_t t) {
//       switch (t) {
//   #define PDR_TYPE_ENTRY(type, count) case type: return count;
//       PDR_TYPE_LIST
//   #undef PDR_TYPE_ENTRY
//       default: return 0;
//       }
//   }
//
#define PDR_TYPE_LIST \
    PDR_TYPE_ENTRY(1, 2) \
    PDR_TYPE_ENTRY(2, 1) \
    PDR_TYPE_ENTRY(3, 1) \
    PDR_TYPE_ENTRY(4, 1) \
    PDR_TYPE_ENTRY(5, 1) \
    PDR_TYPE_ENTRY(6, 1) \
    PDR_TYPE_ENTRY(7, 1) \
    PDR_TYPE_ENTRY(8, 1) \
    PDR_TYPE_ENTRY(9, 1) \
    PDR_TYPE_ENTRY(10, 1) \
    PDR_TYPE_ENTRY(11, 1) \
    PDR_TYPE_ENTRY(12, 1) \
    PDR_TYPE_ENTRY(13, 1) \
    PDR_TYPE_ENTRY(14, 1) \
    PDR_TYPE_ENTRY(15, 2) \
    PDR_TYPE_ENTRY(16, 1) \
    PDR_TYPE_ENTRY(17, 1) \
    PDR_TYPE_ENTRY(18, 1) \
    PDR_TYPE_ENTRY(19, 1) \
    PDR_TYPE_ENTRY(20, 1) \
    PDR_TYPE_ENTRY(21, 1) \
    PDR_TYPE_ENTRY(22, 1) \
    PDR_TYPE_ENTRY(23, 1) \
    PDR_TYPE_ENTRY(24, 1) \
    PDR_TYPE_ENTRY(25, 1) \
    PDR_TYPE_ENTRY(30, 1) \
    PDR_TYPE_ENTRY(126, 1) \
    PDR_TYPE_ENTRY(127, 1)

void pdr_repo_populate_ext(pdr_repo_t *repo, void *ctx);
void pdr_repo_populate(pdr_repo_t *repo, void *ctx);

#endif // PDR_GENERATED_H_
