/**
 * @file pldm_pdr_repo_example.c
 * @brief Example: load code_gen.py output into pdr_repo, then exercise every API
 *
 * Pipeline:
 *   1. python3 code_gen.py source/data source/schema output/pdr_generated.c \
 *        --macros source/data/macro_defs.yaml
 *   2. gcc -o pdr_example source/pldm_pdr_repo.c \
 *        output/pdr_generated.c source/pldm_pdr_repo_example.c \
 *        -Isource -Wall
 *   3. ./pdr_example
 */

#include <stdio.h>
#include "pldm_pdr_repo.h"

/* ----------------------------------------------------------------
 * PDR type codes (DSP0248 Table 28) used in this example
 * ---------------------------------------------------------------- */
#define PDR_TYPE_TERMINUS_LOCATOR    1
#define PDR_TYPE_NUMERIC_SENSOR      2
#define PDR_TYPE_NUMERIC_SENSOR_INIT 3
#define PDR_TYPE_STATE_SENSOR        4
#define PDR_TYPE_FRU_RECORD_SET     20
#define PDR_TYPE_OEM_DEVICE        126

/* ----------------------------------------------------------------
 * Extern: generated by code_gen.py -> output/pdr_generated.c
 * ---------------------------------------------------------------- */
extern void pdr_repo_populate_ext(pdr_repo_t *repo, void *ctx); /* fast zero-copy init */
extern void pdr_repo_populate(pdr_repo_t *repo, void *ctx);     /* rebuild callback    */

/* ----------------------------------------------------------------
 * Helper: print repository info
 * ---------------------------------------------------------------- */
static void print_repo_info(const pdr_repo_t *repo)
{
    const pdr_repo_info_t *info = pdr_repo_get_info(repo);

    printf("=== Repository Info ===\n");
    printf("  State            : %s\n",
           info->repository_state == 0 ? "available" : "updating");
    printf("  Record count     : %u\n", info->record_count);
    printf("  Repository size  : %u bytes\n", info->repository_size);
    printf("  Largest record   : %u bytes\n", info->largest_record_size);
    printf("\n");
}

/* ----------------------------------------------------------------
 * Helper: walk all records from handle 0 to end
 * ---------------------------------------------------------------- */
static void dump_all_records(const pdr_repo_t *repo)
{
    uint32_t handle = 0; /* 0 = "get the first record" */

    printf("=== All Records ===\n");
    while (1) {
        uint32_t       next_record_handle;
        uint32_t       next_data_handle;
        uint8_t        transfer_flag;
        const uint8_t *data;
        uint16_t       data_len;

        int rc = pdr_repo_get_pdr(repo, handle, 0,
                                  &next_record_handle,
                                  &next_data_handle,
                                  &transfer_flag,
                                  &data, &data_len);
        if (rc != 0) {
            break;
        }

        const pldm_pdr_hdr_t *hdr = (const pldm_pdr_hdr_t *)data;
        printf("  Handle %2u : type=%3u, total_size=%3u, payload=%3u bytes\n",
               hdr->record_handle,
               hdr->pdr_type,
               data_len,
               hdr->data_length);

        if (next_record_handle == 0) {
            break;
        }
        handle = next_record_handle;
    }
    printf("\n");
}

/* ----------------------------------------------------------------
 * Helper: find & print all records of a given PDR type
 * ---------------------------------------------------------------- */
static void find_all_by_type(const pdr_repo_t *repo,
                             uint8_t pdr_type, const char *label)
{
    uint32_t       found, next;
    const uint8_t *data;
    uint16_t       len;
    uint32_t       search_from = 0;
    int            count = 0;

    printf("--- FindPDR: type=%u (%s) ---\n", pdr_type, label);
    while (pdr_repo_find_pdr(repo, pdr_type,
                             search_from, &found, &next,
                             &data, &len) == 0)
    {
        printf("  [%d] handle=%u, size=%u bytes\n", count++, found, len);
        if (next == 0) {
            break;
        }
        search_from = found;
    }
    if (count == 0) {
        printf("  (none found)\n");
    }
    printf("\n");
}

/* ================================================================
 * Main
 * ================================================================ */
int main(void)
{
    static pdr_repo_t repo;
    int rc;

    /* ============================================================
     * 1. Initialize and populate with generated data (zero-copy)
     *    Uses pdr_repo_populate_ext() from output/pdr_generated.c
     * ============================================================ */
    printf("--- 1. Init (zero-copy populate_ext) ---\n");
    pdr_repo_populate_ext(&repo, NULL);
    print_repo_info(&repo);

    /* ============================================================
     * 2. Walk every record (GetPDR from handle 0 to end)
     * ============================================================ */
    printf("--- 2. Dump all records ---\n");
    dump_all_records(&repo);

    /* ============================================================
     * 3. FindPDR — search by type
     *    Show how to enumerate all records of a specific PDR type.
     * ============================================================ */
    printf("--- 3. FindPDR examples ---\n");
    find_all_by_type(&repo, PDR_TYPE_TERMINUS_LOCATOR, "Terminus Locator");
    find_all_by_type(&repo, PDR_TYPE_NUMERIC_SENSOR,   "Numeric Sensor");
    find_all_by_type(&repo, PDR_TYPE_STATE_SENSOR,     "State Sensor");
    find_all_by_type(&repo, PDR_TYPE_FRU_RECORD_SET,   "FRU Record Set");
    find_all_by_type(&repo, PDR_TYPE_OEM_DEVICE,       "OEM Device");

    /* ============================================================
     * 4. GetPDR — fetch a specific record by handle
     * ============================================================ */
    printf("--- 4. GetPDR for handle 1 ---\n");
    {
        uint32_t       next_rec, next_data;
        uint8_t        xfer_flag;
        const uint8_t *data;
        uint16_t       len;

        rc = pdr_repo_get_pdr(&repo, 1, 0,
                              &next_rec, &next_data, &xfer_flag,
                              &data, &len);
        if (rc == 0) {
            const pldm_pdr_hdr_t *hdr = (const pldm_pdr_hdr_t *)data;
            printf("  type=%u, size=%u, transfer_flag=0x%02X, next_record=%u\n",
                   hdr->pdr_type, len, xfer_flag, next_rec);
            printf("  First 8 payload bytes: ");
            const uint8_t *payload = data + sizeof(pldm_pdr_hdr_t);
            for (int i = 0; i < 8 && i < hdr->data_length; i++) {
                printf("0x%02X ", payload[i]);
            }
            printf("\n");
        }
    }
    printf("\n");

    /* ============================================================
     * 5. Signature (CRC32)
     * ============================================================ */
    printf("--- 5. Repository signature ---\n");
    uint32_t sig1 = pdr_repo_get_signature(&repo);
    printf("  CRC32          = 0x%08X\n", sig1);
    uint32_t sig2 = pdr_repo_get_signature(&repo);
    printf("  Cached (same?) = 0x%08X (%s)\n", sig2,
           sig1 == sig2 ? "yes" : "no");
    printf("\n");

    /* ============================================================
     * 6. Add a record at runtime (on top of generated data)
     * ============================================================ */
    printf("--- 6. Add a record at runtime ---\n");
    {
        uint8_t  extra_payload[] = { 0xDE, 0xAD, 0xBE, 0xEF };
        uint32_t new_handle;
        rc = pdr_repo_add_record(&repo, PDR_TYPE_NUMERIC_SENSOR,
                                 extra_payload, sizeof(extra_payload),
                                 &new_handle);
        printf("  Added runtime sensor -> handle=%u (rc=%d)\n", new_handle, rc);
        print_repo_info(&repo);

        /* Signature must have changed */
        uint32_t sig3 = pdr_repo_get_signature(&repo);
        printf("  New signature  = 0x%08X (changed=%s)\n",
               sig3, sig3 != sig1 ? "yes" : "no");

        /* Search confirms the new record is findable */
        find_all_by_type(&repo, PDR_TYPE_NUMERIC_SENSOR, "Numeric Sensor (after add)");
    }

    /* ============================================================
     * 7. Remove a record
     * ============================================================ */
    printf("--- 7. Remove handle 1 ---\n");
    rc = pdr_repo_remove_record(&repo, 1);
    printf("  rc=%d\n", rc);
    print_repo_info(&repo);

    /* ============================================================
     * 8. RunInitAgent — wipe & rebuild to clean state
     * ============================================================ */
    printf("--- 8. RunInitAgent again (wipe & rebuild) ---\n");
    rc = pdr_repo_run_init_agent(&repo, pdr_repo_populate, NULL);
    printf("  rc=%d\n", rc);
    print_repo_info(&repo);

    printf("Done.\n");
    return 0;
}
